---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-operator
spec:
  selector:
    matchLabels:
      app: my-operator
  replicas: 1
  template:
    metadata:
      labels:
        app: my-operator
    spec:
      serviceAccountName: my-operator
      containers:
      - name: operator
        image: k8s-operator:0.0.1-SNAPSHOT
        imagePullPolicy: Never
        ports:
        - containerPort: 8080