apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator-sa

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-operator
spec:
  selector:
    matchLabels:
      app: my-operator
  replicas: 1
  template:
    metadata:
      labels:
        app: my-operator
    spec:
      serviceAccountName: operator-sa
      containers:
      - name: operator
        image: k8s-operator:0.0.1-SNAPSHOT
        imagePullPolicy: Never
        ports:
        - containerPort: 8080

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: operator-role-binding
subjects:
- kind: ServiceAccount
  name: operator-sa
  namespace: operator-test
roleRef:
  kind: ClusterRole
  name: operator-role
  apiGroup: ""

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-role
rules:
- apiGroups:
  - ""
  resources:
  - deployments
  - services
  - configmaps
  - pods
  verbs:
  - '*'
- apiGroups:
  - "apps"
  resources:
  - deployments
  - services
  - configmaps
  verbs:
  - '*'
- apiGroups:
  - "apiextensions.k8s.io"
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - "com.blax.operator"
  resources:
  - ac
  - airconds
  - ac/status
  - airconds/status
  verbs:
  - '*'
