apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: operator-role-binding
subjects:
  - kind: ServiceAccount
    name: operator-sa
    namespace: operator-test
roleRef:
  kind: ClusterRole
  name: operator-role
  apiGroup: ""

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-role
rules:
  - apiGroups:
      - ""
    resources:
      - deployments
      - services
      - configmaps
      - pods
    verbs:
      - '*'
  - apiGroups:
      - "apps"
    resources:
      - deployments
      - services
      - configmaps
    verbs:
      - '*'
  - apiGroups:
      - "apiextensions.k8s.io"
    resources:
      - customresourcedefinitions
    verbs:
      - '*'
  - apiGroups:
      - "com.blax"
    resources:
      - ac
      - airconds
      - ac/status
      - airconds/status
    verbs:
      - '*'
